### ISSUE TITLE
How can I evaluate the IBD segments of a trios??

### ISSUE THREAD

**Issue by zxy1555847** [browning-lab/hap-ibd#11]
Firstly, thank you so much for developing such a great tool!
But I meet a problem.
I have a Arrays VCF of a trios containing approximately 500,000 loci.  
I want to calculate daughter's chromosomes come from which chromosome segments of mom and dad respectively,  in other words, see where each of the mom's and dad's recombination occurred.
But after I prepare for the phased VCF and PLINK map, the result IBD and HBD file is empty. 
So I want to ask that there are some method such as parameter  adapt can meet my analytical needs?

**Comment by browning-lab** [comment]
The hap-ibd program is designed for analyzing large data sets that have
highly-accurate genotypes and haplotypes. The empty IBD output file is
probably due to errors in the input haplotypes.  You could try to improve
haplotype accuracy by excluding very low frequency alleles and phasing your
data with the aid of a large reference panel.
